animations {
    enabled = true

    bezier = cleanCurve, 0.16, 1, 0.3, 1

    animation = windows, 1, 5, cleanCurve, slide
    animation = windowsOut, 1, 5, cleanCurve, slide
    animation = fade, 1, 5, cleanCurve
    animation = workspaces, 1, 4, cleanCurve, slide
}
