decoration {
    rounding = 20

    active_opacity = 0.75
    inactive_opacity = 0.50

#    shadow:enabled = true
#    shadow:range = 15
#    shadow:render_power = 3
#   shadow:color = rgba(9d6b9955)

    blur {
        enabled = true
        size = 5
        passes = 5
        new_optimizations = true
        xray = false
    }
}
