# Reglas de ventana
windowrule {
    name = firefox-custom
    match:class = ^(firefox)$

    opaque = true
    no_blur = true
}

windowrule {
    name = kitty-noblur
    match:class = ^(kitty)$

    no_blur = true
}

windowrule {
    name = kitty-nvim-blur
    match:class = ^(kitty)$
    match:title = .*nvim.*
 
    no_blur = false
}

windowrule {
    name = eww-music-blur
    match:class = ^(eww-music_popup)$
 
    no_blur = false
}
 
windowrule {
    name = eww-music-blur
    match:title = ^(music_popup)$
    no_blur = false
}

