# Colores fundamentales
background            #0D0819
foreground            #9D6B99
cursor                #0D0819
selection_background  #B28AAF
selection_foreground  #502C55

# Cursor colors
cursor                  #5B2A62
cursor_text_color       #2E1839

url_color               #70416F

# Configuración Estética de Pestañas
active_tab_background   #b0d4de
active_tab_foreground   #ffb7c5
active_tab_font_style   bold

inactive_tab_background #1e222a
inactive_tab_foreground #b8c5f2
inactive_tab_font_style normal

tab_bar_background      #181a20

# Color de la Barra de Título (Wayland)
wayland_titlebar_color  #1e222a

# Marcas de búsqueda (Mark 1, 2 y 3)
mark1_foreground        #1e222a
mark1_background        #ffb7c5
mark2_foreground        #1e222a
mark2_background        #a0e0e4
mark3_foreground        #1e222a
mark3_background        #b8c5f2

# Terminal Colors
color0  #282c34
color8  #3f444a

color1  #f3a0b3
color9  #ffb7c5

color2  #a0e0e4
color10 #bbf2f6

color3  #b8c5f2
color11 #d2dafa

color4  #b0d4de
color12 #cbe7ee

color5  #ffb7c5
color13 #ffd1dc
