# Colores fundamentales
background            #110f18
foreground            #a5a1b8
cursor                #cba6f7
selection_background  #241f31
selection_foreground  #cba6f7
# Cursor colors
cursor                  #cba6f7
cursor_text_color       #110f18

url_color               #f5c2e7
# Configuración Estética de Pestañas
active_tab_background   #241f31
active_tab_foreground   #cba6f7
active_tab_font_style   bold

inactive_tab_background #110f18
inactive_tab_foreground #575268
inactive_tab_font_style normal

tab_bar_background      #0b0a10

# Color de la Barra de Título (Wayland)
wayland_titlebar_color  #110f18
# Marcas de búsqueda (Mark 1, 2 y 3)
mark1_foreground        #110f18
mark1_background        #cba6f7
mark2_foreground        #110f18
mark2_background        #f5c2e7
mark3_foreground        #110f18
mark3_background        #a5a1b8

# Black
color0  #110f18
color8  #575268

# Red 
color1  #e06c75
color9  #f5c2e7

# Green
color2  #98c379
color10 #b5e890

# Yellow
color3  #e5c07b
color11 #efd49f

# Blue 
color4  #cba6f7
color12 #d8b4fe

# Magenta
color5  #f5c2e7
color13 #ffcff5

# Cyan
color6  #89dceb
color14 #a6e3a1

# White
color7  #a5a1b8
color15 #cdd6f4
