require("colors")

require("config.monitors")
require("config.autostart")
require("config.cursor")
require("config.general")
require("config.animations")
require("config.input")
require("config.windowsrules")
require("config.keybinds")
require("config.env")
require("config.layerrule")
require("config.layout")
