include theme-kitty.conf
# Tipografía
font_family      		FiraCode Nerd Font
bold_font        		auto
italic_font      		auto
bold_italic_font	 	auto
font_size 	 		9.0
# Interlineado
modify_font 			line_height 110%
# --- TRANSPARENCIA ---
background_opacity 0.85
# --- SHELL PREDETERMINADO ---
shell 				zsh
#silence the terminal
enable_audio_bell		no
#Especiales
map ctrl+shift+c 		copy_to_clipboard
map ctrl+shift+v 		paste_from_clipboard
copy_on_select		  	yes
mouse__hide_wait	  	0
select_by_word_characters 	@-./_~?&=+"a
allow_remote_control yes
# Estilo del Cursor
cursor_shape			beam
cursor_stop_blinking_after	0
cursor_trail			10
cursor_trail_derey		0.15 0.4
cursor_trail_start_threshold	2
scrollback_lines		2000
# Bordes
active_border_color		#E3D9FC
inactive_border_color		#4928C2
# Estilo de la Barra de Pestañas
tab_bar_style			powerline
remember_window_size		no
draw_minimal_borders		yes
window_padding_width		10
confirm_os_window_close 	0
window_border_width		1pt
